import glob
import json
import os
from PIL import Image, ImageDraw, ImageFont
from trainer.global_configs import FONTS_DIR, OUTPUT_DIR
import matplotlib.pyplot as plt
import numpy as np

from utils.draw_text_in_bbox import draw_text_in_bbox


def combine_images_based_on_layout_dm(output_path=OUTPUT_DIR, font_path=f'{FONTS_DIR}/KohSantepheap-Regular.ttf', verbatim=False):
    """
    predicted_layout: {"testheader.header":(40, 50,500,300),"backgroundo.png":(100, 100, 200, 50),
    "iamtext.txt":(200, 200, 100, 100),
    "Cosmetic_Logo.png":(200, 200, 100, 100), 
    "Cosmetic_Logo copy.png":(10, 50, 100, 100)},
    output_path: "./here_my_output_image.png"
    """

    # read predicted_layouts.json
    filepath = f"{OUTPUT_DIR}/predicted_layouts.json"
    with open(filepath) as f:
        predicted_layouts = json.load(f)
    
    # for each predicted_layout in predicted_layouts generate output
    n_pages = len(predicted_layouts)
    if verbatim:
        print(20*'#', ' Output - combined images with layout generated by layout-dm', 20*'#')
        fig = plt.figure(figsize = (60, 40))
    for page in range(n_pages):
        # input for this function
        predicted_layout = predicted_layouts[str(page)]
                
        # create an empty list to store the inputs objects and coordinates
        image_list = []
        coordinates_list = []
        text_list = []
        header_list = []
        
        # run over dico of items
        for file_path, coordinates in predicted_layout.items():
            try:
                #handeling images
                if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
                    #open the image file using PIL
                    image = Image.open(file_path)
                    # convert image to RGBA mode
                    image = image.convert("RGBA")
                    # append the image object and coordinates to the respective lists
                    image_list.append(image)
                    coordinates_list.append(coordinates)
                # handeling texts
                elif file_path.lower().endswith(('.txt')):
                    # read text file contents
                    with open(file_path, 'r') as file:
                        text = file.read()
                    # append the text and coordinates to the respective lists
                    text_list.append((text, coordinates))

                # handeling headers
                elif file_path.lower().endswith(('.header')):
                    # read text file contents
                    with open(file_path, 'r') as file:
                        header = file.read()
                    # append the header and coordinates to the respective lists
                    header_list.append((header, coordinates))
            except IOError:
                print("Unable to open file:", file_path)
        
        # get the dimensions of the first image
        width, height = image_list[0].size
        
        # create a new blank image with the combined size
        combined_image = Image.new("RGBA", (width, height))
        
        # iterate though the image list and paste each image onto the combined image using the corresponding coordinates
        for image, coordinates in zip(image_list, coordinates_list):
            shifted_coordinates = (coordinates[0] - coordinates[2]//2, coordinates[1] - coordinates[3]//2)
            combined_image.paste(image, shifted_coordinates, image)
        
        # generate a text layer
        draw = ImageDraw.Draw(combined_image)
        for text, coordinates in text_list:
            text_position = (coordinates[0], coordinates[1])
            shifted_text_position = (coordinates[0] - coordinates[2]//2, coordinates[1] - coordinates[3]//2)
            text_color = (255, 255, 255)  # Colot for the text (set to white)
            font = ImageFont.truetype(font_path, 20)  # font type and size for text
            draw.text(shifted_text_position, text, fill=text_color, font=font)

        # generate a text layer
        #draw = ImageDraw.Draw(combined_image)
        for header, coordinates in header_list:
            
            draw_text_in_bbox(coordinates, font_path, header, combined_image)

            #header_position = (coordinates[0], coordinates[1])
            #shifted_header_position = (coordinates[0] - coordinates[2]//2, coordinates[1] - coordinates[3]//2)
            #text_color = (255, 255, 255)  # color for the header (set to white)
            #font = ImageFont.truetype(font_path, 100)  # font type and size for header
            #draw.text(shifted_header_position, header, fill=text_color, font=font)
        
        # save the combined image to the specified output path
        output_path_name = os.path.join(output_path, f'combined-images_option-{page}.png')
        combined_image.save(output_path_name)
        ## print
        if verbatim:
            input_print = {os.path.basename(key): val for key, val in predicted_layout.items()}
            print(f"\nPage {page}\nInput: {input_print}\nCombined image saved to: {output_path_name}\n")


        # Visualization of outputs
        if verbatim:
            img_array = np.array(combined_image)
            ax = fig.add_subplot(1, n_pages, (page+1))
            ax.imshow(img_array)
            ax.axis('off')
    plt.show()